name: Deploy

on:
  workflow_run:
    workflows: ["E2E"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying..."
